version: '3.4'
services:
    fc.codeflix.catalog.db:
      hostname: catalogdb
      container_name: catalogdb
      image: mysql
      ports:
        - 3306:3306
      environment:
        MYSQL_ROOT_PASSWORD: C0D3fl1x.0
      networks:
        - service_catalog
      volumes:
         - ./container-volume/mysql-data:/var/lib/mysql

    rabbitmq:
        container_name: adm_video_rabbitmq
        image: rabbitmq:3-management
        hostname: rabbitmq
        environment:
            - RABBITMQ_DEFAULT_USER=codeflix
            - RABBITMQ_DEFAULT_PASS=123456
        ports:
            - 15672:15672
            - 5672:5672
        networks:
            - service_catalog
        volumes:
            - ./container-volume/rabbitmq-data:/var/lib/rabbitmq/mnesia
    
    keycloack:
        container_name: ad_videos_keycloack
        image: quay.io/keycloak/keycloak:20.0.3
        hostname: keycloack
        environment:
            - KEYCLOAK_ADMIN=admin
            - KEYCLOAK_ADMIN_PASSWORD=admin
            - KEY_CLOAK_USER=codeflix   
            - KC_DB=mysql
            - KC_DB_URL_HOST=catalogdb
            - KC_DB_URL_PORT=3306
            - KC_DB_SCHEMA=keycloak
            - KC_DB_USERNAME=root
            - KC_DB_PASSWORD=C0D3fl1x.0
        ports:
            - 8443:8080
        command:
            - start-dev
        depends_on:
            - fc.codeflix.catalog.db
        networks:
            - service_catalog
    
networks:
  service_catalog:
    name: service_catalog
    
