version: '3.4'
services:
    fc.codeflix.catalog.db:
      hostname: catalogdb
      container_name: catalogdb
      image: mysql
      ports:
        - 3306:3306
      environment:
        MYSQL_ROOT_PASSWORD: C0D3fl1x.0

networks:
    default:
        name: service_catalog
  