version: '3.4'
services:
    app:
        container_name: adm_video_app
        image: deividroger/fc-codeflix-catalog:latest
        ports:
            - 5000:80
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://+:80
            - GOOGLE_APPLICATION_CREDENTIALS=/app/gcp_credentials.json
        volumes:
            - ./src/FC.CodeFlix.Catalog.Api/gcp_credentials.json:/app/gcp_credentials.json
        depends_on:
            - fc.codeflix.catalog.db
            - rabbitmq
            - Keycloak
            - filebeat
        networks:
            - service_catalog
        restart: 
            unless-stopped
        labels:
            filebeat_collector: true
            decode_log_event_to_json_object: true

    fc.codeflix.catalog.db:
      hostname: catalogdb
      container_name: catalogdb
      image: mysql
      ports:
        - 3306:3306
      environment:
        MYSQL_ROOT_PASSWORD: C0D3fl1x.0
      networks:
        - service_catalog
      volumes:
        - .docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

    rabbitmq:
        container_name: adm_video_rabbitmq
        image: rabbitmq:3-management
        hostname: rabbitmq
        environment:
            - RABBITMQ_DEFAULT_USER=codeflix
            - RABBITMQ_DEFAULT_PASS=123456
        ports:
            - 15672:15672
            - 5672:5672
        networks:
            - service_catalog
        volumes:
            - .docker/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
            - .docker/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
    
    Keycloak:
        container_name: ad_videos_keycloack
        image: quay.io/keycloak/keycloak:20.0.3
        hostname: Keycloak
        environment:
            - KEYCLOAK_ADMIN=admin
            - KEYCLOAK_ADMIN_PASSWORD=admin
            - KEY_CLOAK_USER=codeflix   
            - KC_DB=mysql
            - KC_DB_URL_HOST=catalogdb
            - KC_DB_URL_PORT=3306
            - KC_DB_SCHEMA=keycloak
            - KC_DB_USERNAME=root
            - KC_DB_PASSWORD=C0D3fl1x.0
        volumes:
            - .docker/keycloak:/opt/keycloak/data/import
        ports:
            - 8443:8080
        command:
            - start-dev --import-realm
        depends_on:
            - fc.codeflix.catalog.db
        networks:
            - service_catalog
        restart: 
            unless-stopped

    filebeat:
        container_name: adm_videos_filebeat
        image: docker.elastic.co/beats/filebeat:7.17.10
        command: filebeat -e -strict.perms=false
        volumes:
        - /var/lib/docker/containers:/var/lib/docker/containers:ro           # Docker logs
        - /var/run/docker.sock:/var/run/docker.sock:ro                       # Additional information about containers
        - .docker/filebeat/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro # Configuration file
        - .docker/filebeat:/usr/share/filebeat/data:rw                    # Persistence data
        user: root                                                             # Allow access to log files and docker.sock
        restart: on-failure
        networks:
            - service_catalog
networks:
  service_catalog:
    name: service_catalog
    
